language: java

sudo: false

addons:
  hosts:
    - world

services:
  - docker

install:
  - docker build -t database db/.
  - docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306 database
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  - mvn clean

jobs:
  include:
    - stage: unit tests
      install: skip
      jdk: oraclejdk11
      script: mvn test -Dtest=com.napier.sem.TestWorldApp
    - stage: integration tests
      jdk: oraclejdk11
      script: mvn test -Dtest=com.napier.sem.AppIntegrationTest
    - stage: GitHub Release
      install: skip
      jdk: oraclejdk11
      script:
        - echo "Deploying to GitHub Releases"
        - mvn package -DskipTests=true -Dmaven.javadoc.skip=true
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name "Patrick Sawyer"
        - git config --local user.email "Patrickpsawyer@gmail.com"
        # Create temporary tag from date and Git log.
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d')-$(git log --format=%h -1)}
        # Set tag
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        # Copy built JAR file.  JAR built in $TRAVIS_BUILD_DIR/
        file: $TRAVIS_BUILD_DIR/target/seMethods-0.1.0.4-jar-with-dependencies.jar
        skip_cleanup: true

stages:
  - unit tests
  - integration tests
  - name: GitHub Release
    if: branch = feature #Remember change this to the branch that is committed.

after_success:
  - bash <(curl -s https://codecov.io/bash)