version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .

    # for debugging allows us to just repackage to get jar into docker app container

  # world db sql file in the world folder
  db:
    build: ""
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33060:3306"